version: '3'
services:
  cockroach:
    network_mode: host
    image: cockroachdb/cockroach:v23.1.12
    ports:
      - '26257:26257'
      - '8080:8080'
    volumes:
      - roach-single-certs:/cockroach/certs
      - roach-single-data:/cockroach/cockroach-data
    environment:
      COCKROACH_DATABASE: cockroach
      COCKROACH_USER: cockroach
      COCKROACH_PASSWORD: cockroach
    command: start-single-node --http-addr=localhost:8080 --insecure

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
#    configs:
#      - source: qdrant_config
#        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant_data

  # rabbitmq:
  #   network_mode: host
  #   image: rabbitmq:3-management
  #   volumes:
  #       - rabbitmq-data:/var/lib/rabbitmq
  #       - rabbitmq-log:/var/log/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest

  # cache:
  #   image: redis:latest
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass guest
  #   volumes:
  #     - cache:/data

#configs:
#  qdrant_config:
#    content: |
#      log_level: INFO

volumes:
  roach-single-certs:
  roach-single-data:
  rabbitmq-data:
  rabbitmq-log:
  cache:
  qdrant_data: